
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'BugsB',
  description: 'Generated by create next app',
}
import Loader from '@/components/loader'
import ContextProvider from '@/Context/ContextProvider'
import Navbar from '@/components/navbar'
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ContextProvider> 
          <Navbar/>
          {children}
        </ContextProvider>
      </body>
    </html>
  )
}
